[green_agent]
image = "ghcr.io/radmanesh/agentbeats-design2code-design2code-agent:latest"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", LOG_LEVEL=INFO }

[[participants]]
# agentbeats_id = ""
name = "design2code-agent"
image = "ghcr.io/radmanesh/agentbeats-design2code-design2code-evaluator:latest"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[config]
# Add your assessment config here
num_tasks = 3
